### ISSUE TITLE
German translation for "qeb" makes no sense. Don't have a better one, though...

### ISSUE THREAD

**Issue by Cyberman-tM** [De7vID/klingon-assistant-data#275]
I'm writing this as an "issue" because I don't have a good suggestion for a replacement.

However, the current word "Schusdek instrument" makes no sense - neither Google nor Wikipedia even seem to KNOW the word.
Even if it would be a specialized word, I think either of them should find something.

However, I don't know how to translate "windbag instrument" unless you want to describe it. As far as I can tell, that isn't a correct specification in english either (which may make sense, as the correct specifications are rather abstract. Bagpipes are classified as "woodwind"...)

"Luftbeutel-Instrument" would be a more literal translation, perhaps no more awkward that "windbag instrument" ?
(The actual literal translation would be "Windbeutel", but that is mainly the german name for profiteroles - I don't think it's a word actually used for instruments.)

**Comment by De7vID** [comment]
Neither Google nor Wikipedia knows the word "Schusdek" because it's a transliteration of the Klingon word **SuSDeq** (see that entry). However, that isn't a good word to use there because it's not a direct translation of the English "windbag".

A "windbag instrument" is a category of musical instruments in English. It includes bagpipes and accordions. It's a musical instrument where wind is collected into a bag which is squeezed to make sound. Would Germans understand "Windsack" for this?

**Comment by Cyberman-tM** [comment]
Hm. I suppose "Windsack" could be understood, but it's again ambigous because that's the word for a "windsock".
I *think* "Luftsack" might be a better word, even if it sounds somewhat weird. Wikipedia has a disambiguation page for it where it's even mentioned that "Luftsack" is part of the bagpipes.

Either way I think there is no good way to do this.
