### ISSUE TITLE
Should boQwI' know ungrammatical but canonical stuff?

### ISSUE THREAD

**Issue by Cyberman-tM** [De7vID/klingon-assistant-data#301]
For example the suffixes -luH and -la' .
Apparently both are canonical, but definitely ungrammatical. Yet people use them. Rarely, fortunately, but I've recently encountered -luH and wasn't able to decipher it until someone pointed me toward those ungrammatical suffixes.

I was surprised that boQwI' doesn't know them - oversight or intentional?

IMO they should be listed - with strong warnings against their use.

[edit] Those suffixes com from KGT it seems:
http://klingonska.org/dict/?q=-luH

**Comment by De7vID** [comment]
It's intentional. See: https://github.com/De7vID/klingon-assistant-data/blob/6957f9a0b206ef49b2f6816cd6f5fb998319633f/mem-26-suffixes.xml#L1463

**boQwI'** is rather strict when it comes to its grammar analysis, because a lot of beginners and learners rely on it. The original thought behind this is that if you were advanced enough to be conversing with people who knew about **-luH** and **-la'**, you wouldn't need **boQwI'** to tell you that they exist. They're explicitly noted as being ungrammatical in KGT, and they're not given definitions independent of being a combination of two other suffixes. The fact that they're canonical is not enough to justify their inclusion in itself; after all, there are dialectical words which are canonical but missing from **boQwI'**, which is supposed to handle grammatical standard dialect.

Maybe they should be included, and marked as you suggest. But to get them to work in the analyser would require a code change here: https://github.com/De7vID/klingon-assistant-android/blob/58bf3bdf252ca2926bd03cd7871af93da2320a5b/app/src/main/java/org/tlhInganHol/android/klingonassistant/KlingonContentProvider.java#L1829

Without the code change, entering a word or sentence using one of these suffixes would not result in the suffix being found, and thus would not solve your problem. But I'm loathe to make any code changes right now as the code is extremely fragile. If this is implemented, it will have to be part of a new code base.

If there were a mode toggle for advanced grammar, enabling **-luH** and **-la'** would definitely be one of the things it would do.

**Comment by De7vID** [comment]
@Cyberman-tM If I add these, what are your suggestions for their definitions (in both English and German)?

**Comment by LievenLitaer** [comment]
I also agree that these two artificial suffixes should be in there, so that a beginner can at least find out what they mean when they discover them. (You do list non-canon words for the same reason, I guess.)
For a translation, I'd suggest what KGT p. 182 provides: "one can" / German "man kann", plus a note like "non-grammatical artificial suffix" and of course a short explanation, which you can word better in English than I do.

**Comment by De7vID** [comment]
As it happens, I need to modify the code for the analysis to include {Saghan} as a number-forming element anyway, and it's not incrementally that much harder to test two changes than one change, so I'll make this change too.

**Comment by Cyberman-tM** [comment]
I didn't see the reply any earlier, sorry. I would have suggested ignoring it in the translation - being able to split a word into its potential parts is easier than knowing these ungrammatical suffixes.
It's not unreasonable to expect the user to try different spellings (i.e. splitting into syllables) IMO.

As for translation, I agree with Lieven - take the text from KGT and add a big "ungrammatical!" marker to it.

**Comment by De7vID** [comment]
This will be implemented in the beta version soon.

**Comment by De7vID** [comment]
Beta released to production. You should see this implemented in v2020.02.03a.
